#include "StudioHome4RecipeAuthoring.h"
#include "StudioHome4Recipes.h"
#include "StudioHome4Setup.h"
#include "StudioModel.h"
#include "SStudioHome4Panel.h"
#include "StudioHeadlessSlate.h"
#include "Misc/AutomationTest.h"
#include "Misc/Paths.h"
#if WITH_DEV_AUTOMATION_TESTS
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FStudioHome4ExplicitRecipeRelations,"Studio.Home4.Authoring.ExplicitRecipeRelationshipsAndOriginalParameterBlocks",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FStudioHome4ExplicitRecipeRelations::RunTest(const FString&)
{
    FString Error;FStudioHome4Spec Out;
    for(const auto& R:StudioHome4Recipes::All())TestTrue(TEXT("Every recipe has original parameters and explicit working relationships"),!StudioHome4RecipeAuthoring::Parameters(R.Id).IsEmpty()&&!StudioHome4RecipeAuthoring::Relationship(R.Template).IsEmpty());
    auto Cylinder=[&](const TCHAR* Id){auto S=StudioHome4Recipes::Find(Id)->Template;S.Reference.LengthCells=20;S.Authoring.PrimitiveSizeCells=FVector(20,20,10);S.Lattice.Extents=FIntVector(80,80,40);S.Authoring.BenchmarkConvention=TEXT("diameter-reference");return S;};
    auto Osc=Cylinder(TEXT("oscillating-cylinder"));TestTrue(*Error,StudioHome4RecipeAuthoring::Resolve(Osc,Out,Error));TestTrue(TEXT("KC period/amplitude and peak speed retain their explicit meaning"),FMath::IsNearlyEqual(*Out.Geometry.MotionFrequencyCyclesPerStep,.0004,1e-12)&&FMath::IsNearlyEqual(*Out.Geometry.HeaveAmplitudeCells,100/(2*UE_DOUBLE_PI),1e-12)&&Out.Fluids.NuHeavy==.008&&!Out.Reference.SpeedCellsPerStep&&Out.Lattice.Extents==FIntVector(400,400,40));
    auto Spin=Cylinder(TEXT("couette-spin"));const auto Keep=StudioHome4Config::Serialize(Out);TestFalse(TEXT("Unknown rotational convention cannot become an inferred solver default"),StudioHome4RecipeAuthoring::Resolve(Spin,Out,Error));TestEqual(TEXT("Rejected relation is transactional"),StudioHome4Config::Serialize(Out),Keep);Spin.Authoring.BenchmarkConvention=TEXT("spin-omega-radius");TestTrue(*Error,StudioHome4RecipeAuthoring::Resolve(Spin,Out,Error));TestTrue(TEXT("Confirmed radius convention yields exact omega/nu and explicit span"),Out.Geometry.SpinRadiansPerStep==.004&&Out.Fluids.NuHeavy==.004&&Out.Lattice.Extents==FIntVector(240,240,40));
    auto Col=Cylinder(TEXT("colagrossi-wb"));Col.Reference.SpeedCellsPerStep=.02;Col.Reference.Froude=.5;TestTrue(*Error,StudioHome4RecipeAuthoring::Resolve(Col,Out,Error));TestTrue(TEXT("Colagrossi Fr-aware gravity and 8D sponge use actual D"),FMath::IsNearlyEqual(*Out.Fluids.Gravity,.00008,1e-15)&&Out.Fluids.Mobility==.05&&Out.Zones.Sponge==160&&Out.Authoring.ZoneUnits==TEXT("root-cells"));Col.Reference.Froude=1;Col.Fluids.Mobility=.012;TestTrue(*Error,StudioHome4RecipeAuthoring::Resolve(Col,Out,Error));TestTrue(TEXT("Conditional low-Fr mobility never overrides a high-Fr choice"),Out.Fluids.Mobility==.012);
    auto Sed=Cylinder(TEXT("sedimentation"));Sed.Authoring.BenchmarkConvention=TEXT("sedimentation-diameter-fluid-heavy");Sed.Fluids.NuHeavy=.01;Sed.Fluids.RhoHeavy=1;Sed.Fluids.RhoLight=.01;TestTrue(*Error,StudioHome4RecipeAuthoring::Resolve(Sed,Out,Error));TestTrue(TEXT("Ga gravity uses body/heavy ratio independently from phase-density ratio"),FMath::IsNearlyEqual(*Out.Fluids.Gravity,FMath::Square(19.6*.01)/(.25*8000),1e-15)&&Out.Fluids.RhoLight==.01);
    auto Magnus=Cylinder(TEXT("magnus"));Magnus.Geometry.SpinRadiansPerStep=.004;Magnus.Run.RampLength=2;TestTrue(*Error,StudioHome4RecipeAuthoring::Resolve(Magnus,Out,Error));TestTrue(TEXT("Magnus actual typed spin ramp derives from chosen Run duration"),Out.Geometry.SpinRampSteps==800&&Out.Lattice.Extents==FIntVector(600,320,40));const auto M=StudioHome4Authoring::Motion(Out,400);const double Integrated=400*400*400./(800*800.)-.5*400*400*400*400./(800*800*800.);TestTrue(TEXT("Cubic ramp rotates actual body by integrated declared omega"),M.TransformVector(FVector(1,0,0)).Equals(FVector(FMath::Cos(.004*Integrated),FMath::Sin(.004*Integrated),0),1e-10));
    auto Barge=StudioHome4Recipes::Find(TEXT("vugts-barge"))->Template;Barge.Authoring.BenchmarkConvention=TEXT("barge-beam-draft");Barge.Authoring.BenchmarkDraftCells=5;Barge.Authoring.PrimitiveSizeCells=FVector(40,8,8);Barge.Geometry.BodyMotion=TEXT("forced-roll");TestTrue(*Error,StudioHome4RecipeAuthoring::Resolve(Barge,Out,Error));TestTrue(TEXT("Barge actual beam follows declared draft while preserving complete body X/Z"),Out.Authoring.PrimitiveSizeCells==FVector(40,10,8));TestFalse(TEXT("Documented Vugts roll belongs to same supplied forcing family"),StudioHome4Recipes::Departures(Barge).ContainsByPredicate([](const FString& V){return V.Contains(TEXT("bodyMotion"));}));Barge.Geometry.BodyMotion=TEXT("free");TestTrue(TEXT("Undocumented motion still departs"),StudioHome4Recipes::Departures(Barge).ContainsByPredicate([](const FString& V){return V.Contains(TEXT("bodyMotion"));}));
    auto Wave=StudioHome4Recipes::Find(TEXT("breaking-wave-banari"))->Template;Wave.Authoring.WaveLengthCells=100;Wave.Authoring.WaveDepthCells=20;Wave.Authoring.WaterlineCells=30;TestTrue(*Error,StudioHome4RecipeAuthoring::Resolve(Wave,Out,Error));TArray<FVector> Curve;TestTrue(*Error,StudioHome4Setup::WaveCurve(Out,0,64,Curve,Error));TestTrue(TEXT("Applied documented speed/slope satisfy actual wave dispersion"),Out.Lattice.Extents==FIntVector(400,100,120)&&Out.Authoring.WavePeriodSteps&&FMath::IsNearlyEqual(*Out.Authoring.WavePeriodSteps,100/.015,1e-9)&&!Curve.IsEmpty());
    auto Foil=StudioHome4Recipes::Find(TEXT("hydrofoil-parkin"))->Template;Foil.Authoring.BenchmarkConvention=TEXT("foil-cog-chord");Foil.Authoring.WaterlineCells=300;Foil.Geometry.CenterOfGravity=FVector(400,50,100);Foil.Geometry.InitialPositionCells=FVector(350,50,80);TestTrue(*Error,StudioHome4RecipeAuthoring::Resolve(Foil,Out,Error));TestTrue(TEXT("Chosen CoG depth anchor and original source origin translate coherently"),FMath::IsNearlyEqual(Out.Geometry.CenterOfGravity->Z,69.6,1e-12)&&FMath::IsNearlyEqual(Out.Geometry.InitialPositionCells->Z,49.6,1e-12));
    return !HasAnyErrors();
}
IMPLEMENT_SIMPLE_AUTOMATION_TEST(FStudioHome4RecipeRelationsNative,"Studio.HeadlessUI.Home4.Authoring.NativeRecipeRelationsAndIssueFocus",EAutomationTestFlags::EditorContext|EAutomationTestFlags::EngineFilter)
bool FStudioHome4RecipeRelationsNative::RunTest(const FString&)
{
    auto Model=MakeShared<FStudioModel>(FPaths::ProjectDir()/TEXT("tmp/debug/home4-recipe-relations-ui")/FGuid::NewGuid().ToString());auto Draft=MakeShared<FStudioHome4Session>(Model);Draft->ApplyRecipe(TEXT("oscillating-cylinder"));Draft->Set(TEXT("reference.lengthCells"),TEXT("20"));Draft->Set(TEXT("authoring.primitiveSizeCells"),TEXT("20,20,10"));Draft->Set(TEXT("lattice.extents"),TEXT("80,80,40"));Draft->Set(TEXT("authoring.benchmarkConvention"),TEXT("diameter-reference"));
    {auto Panel=SNew(SStudioHome4Panel).Model(Model).Session(Draft).Page(TEXT("Bodies"));FStudioHeadlessSlate UI(*this,Panel,FVector2D(1040,800));UI.Press(TEXT("Home4RecipeResolve"));FStudioHome4Spec S;FString E;TestTrue(*E,Draft->Build(S,E));TestTrue(TEXT("Native recipe action retains actual derived sinusoidal request"),S.Geometry.MotionFrequencyCyclesPerStep==.0004&&Draft->IsDirty());}
    Draft->Set(TEXT("reference.speedCellsPerStep"),TEXT("0.2"));FString RoutedPage,RoutedKey;
    {auto Panel=SNew(SStudioHome4Panel).Model(Model).Session(Draft).Page(TEXT("Bodies")).OnFocusField_Lambda([&](const FString& Page,const FString& Key){RoutedPage=Page;RoutedKey=Key;});FStudioHeadlessSlate UI(*this,Panel,FVector2D(1040,800));UI.Press(TEXT("Home4Issue.reference.speedCellsPerStep"));TestEqual(TEXT("Cross-page issue routes the actual typed editor page"),RoutedPage,FString(TEXT("Fluids & Interface")));TestEqual(TEXT("Cross-page issue carries stable exact field key"),RoutedKey,FString(TEXT("reference.speedCellsPerStep")));}
    {auto Panel=SNew(SStudioHome4Panel).Model(Model).Session(Draft).Page(TEXT("Fluids & Interface"));FStudioHeadlessSlate UI(*this,Panel,FVector2D(1040,800));TestTrue(TEXT("Actual target field exists"),Panel->HasField(RoutedKey));Panel->FocusField(RoutedKey);UI.Layout();TestTrue(TEXT("Issue focus arranges and selects actual retained editor"),Panel->FocusField(RoutedKey));}
    return !HasAnyErrors();
}
#endif
