// Copyright FlowViz contributors. All Rights Reserved.

#include "CFDViz/CFDVizColorMaps.h"
#include "Render/FlowVizColorMapTexture.h"
#include "Misc/AutomationTest.h"

#if WITH_DEV_AUTOMATION_TESTS

/**
 * Colormap conformance against the Python reference implementation.
 *
 * The expected values below are GENERATED by sampling
 * Tools/cfdviz/src/cfdviz/colormaps.py. If this test fails, an Unreal render
 * and a Python reference figure of the same field would show different colors -
 * so it is a correctness failure, not a cosmetic one.
 *
 * Probe positions are deliberately irregular (0.01, 0.3, 0.5001, 0.667, 0.99)
 * so that an off-by-one or half-texel error cannot hide between control points.
 */
IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FCFDVizColorMapTest,
	"FlowViz.CFDViz.ColorMaps",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext
		| EAutomationTestFlags::EngineFilter)

namespace
{
	struct FColorMapProbe
	{
		ECFDVizColorMap Map;
		float Position;
		float R;
		float G;
		float B;
	};

	// GENERATED from the Python reference - do not hand-edit.
	static const FColorMapProbe ExpectedProbes[] = {
		{ ECFDVizColorMap::Viridis, 0.0000f, 0.267004f, 0.004874f, 0.329415f },
		{ ECFDVizColorMap::Viridis, 0.0100f, 0.268254f, 0.015758f, 0.339663f },
		{ ECFDVizColorMap::Viridis, 0.1250f, 0.282623f, 0.140926f, 0.457517f },
		{ ECFDVizColorMap::Viridis, 0.3000f, 0.235063f, 0.307856f, 0.539237f },
		{ ECFDVizColorMap::Viridis, 0.5000f, 0.163625f, 0.471133f, 0.558148f },
		{ ECFDVizColorMap::Viridis, 0.5001f, 0.163596f, 0.471210f, 0.558142f },
		{ ECFDVizColorMap::Viridis, 0.6670f, 0.129962f, 0.597756f, 0.539499f },
		{ ECFDVizColorMap::Viridis, 0.8750f, 0.266941f, 0.748751f, 0.440573f },
		{ ECFDVizColorMap::Viridis, 0.9900f, 0.935143f, 0.893565f, 0.167667f },
		{ ECFDVizColorMap::Viridis, 1.0000f, 0.993248f, 0.906157f, 0.143936f },
		{ ECFDVizColorMap::Plasma, 0.0000f, 0.050383f, 0.029803f, 0.527975f },
		{ ECFDVizColorMap::Plasma, 0.0100f, 0.066667f, 0.028617f, 0.535123f },
		{ ECFDVizColorMap::Plasma, 0.1250f, 0.253935f, 0.014979f, 0.617331f },
		{ ECFDVizColorMap::Plasma, 0.3000f, 0.475680f, 0.020956f, 0.651638f },
		{ ECFDVizColorMap::Plasma, 0.5000f, 0.692840f, 0.165141f, 0.564522f },
		{ ECFDVizColorMap::Plasma, 0.5001f, 0.692924f, 0.165233f, 0.564446f },
		{ ECFDVizColorMap::Plasma, 0.6670f, 0.826180f, 0.317941f, 0.440538f },
		{ ECFDVizColorMap::Plasma, 0.8750f, 0.949217f, 0.517763f, 0.295662f },
		{ ECFDVizColorMap::Plasma, 0.9900f, 0.940751f, 0.938566f, 0.144473f },
		{ ECFDVizColorMap::Plasma, 1.0000f, 0.940015f, 0.975158f, 0.131326f },
		{ ECFDVizColorMap::Inferno, 0.0000f, 0.001462f, 0.000466f, 0.013866f },
		{ ECFDVizColorMap::Inferno, 0.0100f, 0.008338f, 0.003993f, 0.030742f },
		{ ECFDVizColorMap::Inferno, 0.1250f, 0.087411f, 0.044556f, 0.224813f },
		{ ECFDVizColorMap::Inferno, 0.3000f, 0.287809f, 0.054493f, 0.381474f },
		{ ECFDVizColorMap::Inferno, 0.5000f, 0.517933f, 0.132268f, 0.408558f },
		{ ECFDVizColorMap::Inferno, 0.5001f, 0.518051f, 0.132321f, 0.408528f },
		{ ECFDVizColorMap::Inferno, 0.6670f, 0.710331f, 0.225884f, 0.403835f },
		{ ECFDVizColorMap::Inferno, 0.8750f, 0.930513f, 0.411474f, 0.145367f },
		{ ECFDVizColorMap::Inferno, 0.9900f, 0.983734f, 0.951413f, 0.604959f },
		{ ECFDVizColorMap::Inferno, 1.0000f, 0.988362f, 0.998364f, 0.644924f },
		{ ECFDVizColorMap::Magma, 0.0000f, 0.001462f, 0.000466f, 0.013866f },
		{ ECFDVizColorMap::Magma, 0.0100f, 0.007650f, 0.004763f, 0.029690f },
		{ ECFDVizColorMap::Magma, 0.1250f, 0.078815f, 0.054184f, 0.211667f },
		{ ECFDVizColorMap::Magma, 0.3000f, 0.262672f, 0.080722f, 0.408929f },
		{ ECFDVizColorMap::Magma, 0.5000f, 0.482930f, 0.146968f, 0.472039f },
		{ ECFDVizColorMap::Magma, 0.5001f, 0.483047f, 0.147005f, 0.472028f },
		{ ECFDVizColorMap::Magma, 0.6670f, 0.678143f, 0.214547f, 0.440698f },
		{ ECFDVizColorMap::Magma, 0.8750f, 0.912966f, 0.381636f, 0.359630f },
		{ ECFDVizColorMap::Magma, 0.9900f, 0.981126f, 0.942654f, 0.718314f },
		{ ECFDVizColorMap::Magma, 1.0000f, 0.987053f, 0.991438f, 0.749504f },
		{ ECFDVizColorMap::Turbo, 0.0000f, 0.189950f, 0.071760f, 0.232170f },
		{ ECFDVizColorMap::Turbo, 0.0100f, 0.194840f, 0.086209f, 0.264296f },
		{ ECFDVizColorMap::Turbo, 0.1250f, 0.251070f, 0.252370f, 0.633740f },
		{ ECFDVizColorMap::Turbo, 0.3000f, 0.269216f, 0.484540f, 0.934242f },
		{ ECFDVizColorMap::Turbo, 0.5000f, 0.158440f, 0.735510f, 0.923050f },
		{ ECFDVizColorMap::Turbo, 0.5001f, 0.158387f, 0.735614f, 0.922880f },
		{ ECFDVizColorMap::Turbo, 0.6670f, 0.127587f, 0.893586f, 0.631393f },
		{ ECFDVizColorMap::Turbo, 0.8750f, 0.527950f, 0.987270f, 0.235730f },
		{ ECFDVizColorMap::Turbo, 0.9900f, 0.483468f, 0.093545f, 0.028564f },
		{ ECFDVizColorMap::Turbo, 1.0000f, 0.479600f, 0.015830f, 0.010550f },
		{ ECFDVizColorMap::CoolWarm, 0.0000f, 0.229806f, 0.298718f, 0.753683f },
		{ ECFDVizColorMap::CoolWarm, 0.0100f, 0.240652f, 0.310894f, 0.762188f },
		{ ECFDVizColorMap::CoolWarm, 0.1250f, 0.365375f, 0.450915f, 0.859997f },
		{ ECFDVizColorMap::CoolWarm, 0.3000f, 0.566711f, 0.633079f, 0.952837f },
		{ ECFDVizColorMap::CoolWarm, 0.5000f, 0.865003f, 0.865003f, 0.865003f },
		{ ECFDVizColorMap::CoolWarm, 0.5001f, 0.865062f, 0.864855f, 0.864803f },
		{ ECFDVizColorMap::CoolWarm, 0.6670f, 0.935484f, 0.626826f, 0.548639f },
		{ ECFDVizColorMap::CoolWarm, 0.8750f, 0.867254f, 0.354740f, 0.259232f },
		{ ECFDVizColorMap::CoolWarm, 0.9900f, 0.718599f, 0.042691f, 0.158953f },
		{ ECFDVizColorMap::CoolWarm, 1.0000f, 0.705673f, 0.015556f, 0.150233f },
		{ ECFDVizColorMap::BlueWhiteRed, 0.0000f, 0.000000f, 0.000000f, 1.000000f },
		{ ECFDVizColorMap::BlueWhiteRed, 0.0100f, 0.020000f, 0.020000f, 1.000000f },
		{ ECFDVizColorMap::BlueWhiteRed, 0.1250f, 0.250000f, 0.250000f, 1.000000f },
		{ ECFDVizColorMap::BlueWhiteRed, 0.3000f, 0.600000f, 0.600000f, 1.000000f },
		{ ECFDVizColorMap::BlueWhiteRed, 0.5000f, 1.000000f, 1.000000f, 1.000000f },
		{ ECFDVizColorMap::BlueWhiteRed, 0.5001f, 1.000000f, 0.999800f, 0.999800f },
		{ ECFDVizColorMap::BlueWhiteRed, 0.6670f, 1.000000f, 0.666000f, 0.666000f },
		{ ECFDVizColorMap::BlueWhiteRed, 0.8750f, 1.000000f, 0.250000f, 0.250000f },
		{ ECFDVizColorMap::BlueWhiteRed, 0.9900f, 1.000000f, 0.020000f, 0.020000f },
		{ ECFDVizColorMap::BlueWhiteRed, 1.0000f, 1.000000f, 0.000000f, 0.000000f },
		{ ECFDVizColorMap::Grayscale, 0.0000f, 0.000000f, 0.000000f, 0.000000f },
		{ ECFDVizColorMap::Grayscale, 0.0100f, 0.010000f, 0.010000f, 0.010000f },
		{ ECFDVizColorMap::Grayscale, 0.1250f, 0.125000f, 0.125000f, 0.125000f },
		{ ECFDVizColorMap::Grayscale, 0.3000f, 0.300000f, 0.300000f, 0.300000f },
		{ ECFDVizColorMap::Grayscale, 0.5000f, 0.500000f, 0.500000f, 0.500000f },
		{ ECFDVizColorMap::Grayscale, 0.5001f, 0.500100f, 0.500100f, 0.500100f },
		{ ECFDVizColorMap::Grayscale, 0.6670f, 0.667000f, 0.667000f, 0.667000f },
		{ ECFDVizColorMap::Grayscale, 0.8750f, 0.875000f, 0.875000f, 0.875000f },
		{ ECFDVizColorMap::Grayscale, 0.9900f, 0.990000f, 0.990000f, 0.990000f },
		{ ECFDVizColorMap::Grayscale, 1.0000f, 1.000000f, 1.000000f, 1.000000f },
	};
}

bool FCFDVizColorMapTest::RunTest(const FString& Parameters)
{
	using namespace CFDViz::ColorMaps;

	// Tolerance is well below 8-bit quantization (1/255 ~= 0.0039), so this
	// catches real divergence without failing on float rounding.
	constexpr float Tolerance = 1.0e-4f;

	for (const FColorMapProbe& Probe : ExpectedProbes)
	{
		const FLinearColor Actual = Sample(Probe.Map, Probe.Position);
		const FString Context = FString::Printf(TEXT("%s at t=%.4f"),
			*GetName(Probe.Map).ToString(), Probe.Position);

		TestNearlyEqual(*(Context + TEXT(" [R]")), Actual.R, Probe.R, Tolerance);
		TestNearlyEqual(*(Context + TEXT(" [G]")), Actual.G, Probe.G, Tolerance);
		TestNearlyEqual(*(Context + TEXT(" [B]")), Actual.B, Probe.B, Tolerance);
		TestEqual(*(Context + TEXT(" [A]")), Actual.A, 1.0f);
	}

	// Names must match the Python dict keys exactly, since sessions and
	// manifests round-trip colormaps by name across the two implementations.
	TestEqual(TEXT("viridis name"), GetName(ECFDVizColorMap::Viridis), FName(TEXT("viridis")));
	TestEqual(TEXT("hyphenated name preserved"),
		GetName(ECFDVizColorMap::BlueWhiteRed), FName(TEXT("blue-white-red")));

	{
		ECFDVizColorMap Parsed = ECFDVizColorMap::Turbo;
		TestTrue(TEXT("TryParse round-trips"), TryParse(FName(TEXT("coolwarm")), Parsed));
		TestEqual(TEXT("TryParse yields CoolWarm"), Parsed, ECFDVizColorMap::CoolWarm);
		TestFalse(TEXT("TryParse rejects unknown"), TryParse(FName(TEXT("jet")), Parsed));
	}

	// The default must never be a rainbow map: rainbows fabricate visual edges
	// where data is smooth and flatten structure where it is steep.
	TestEqual(TEXT("default is viridis"), Default, ECFDVizColorMap::Viridis);
	TestTrue(TEXT("default is perceptually uniform"), IsPerceptuallyUniform(Default));
	TestFalse(TEXT("turbo is not marked perceptually uniform"),
		IsPerceptuallyUniform(ECFDVizColorMap::Turbo));
	TestTrue(TEXT("coolwarm is diverging"), IsDiverging(ECFDVizColorMap::CoolWarm));
	TestFalse(TEXT("viridis is not diverging"), IsDiverging(ECFDVizColorMap::Viridis));

	// Out-of-range positions clamp to the endpoints rather than wrapping.
	TestEqual(TEXT("clamps below"), Sample(ECFDVizColorMap::Viridis, -5.0f),
		Sample(ECFDVizColorMap::Viridis, 0.0f));
	TestEqual(TEXT("clamps above"), Sample(ECFDVizColorMap::Viridis, 5.0f),
		Sample(ECFDVizColorMap::Viridis, 1.0f));

	// LUT pixel-center sampling. These exact values come from the Python
	// build_lut(), so a half-texel disagreement fails here specifically.
	{
		TArray<FLinearColor> Lut;
		BuildLut(ECFDVizColorMap::Viridis, Lut, 256);
		TestEqual(TEXT("LUT size"), Lut.Num(), 256);
		TestNearlyEqual(TEXT("lut[0].R"),   Lut[0].R,   0.267248f, Tolerance);
		TestNearlyEqual(TEXT("lut[1].G"),   Lut[1].G,   0.011251f, Tolerance);
		TestNearlyEqual(TEXT("lut[127].B"), Lut[127].B, 0.558069f, Tolerance);
		TestNearlyEqual(TEXT("lut[128].R"), Lut[128].R, 0.163062f, Tolerance);
		TestNearlyEqual(TEXT("lut[255].R"), Lut[255].R, 0.981899f, Tolerance);

		// Alpha is reserved for the opacity transfer function and must not be
		// baked into the color LUT.
		for (const FLinearColor& Entry : Lut)
		{
			if (Entry.A != 1.0f)
			{
				AddError(TEXT("Color LUT must not encode opacity; alpha must be 1."));
				break;
			}
		}
	}

	// Reversed LUT mirrors the forward one.
	{
		TArray<FLinearColor> Forward, Reversed;
		BuildLut(ECFDVizColorMap::Viridis, Forward, 64);
		BuildLut(ECFDVizColorMap::Viridis, Reversed, 64, /*bReverse=*/true);
		TestNearlyEqual(TEXT("reversed first == forward last"),
			Reversed[0].R, Forward[63].R, Tolerance);
		TestNearlyEqual(TEXT("reversed last == forward first"),
			Reversed[63].R, Forward[0].R, Tolerance);
	}

	// Banding must produce exactly N distinct colors in equal-length runs.
	{
		TArray<FLinearColor> Banded;
		BuildLut(ECFDVizColorMap::Viridis, Banded, 256, /*bReverse=*/false, /*Bands=*/8);

		int32 Transitions = 0;
		for (int32 Index = 1; Index < Banded.Num(); ++Index)
		{
			if (!Banded[Index].Equals(Banded[Index - 1], 1.0e-6f))
			{
				++Transitions;
				// Each band must span exactly 256/8 = 32 entries.
				TestEqual(TEXT("band boundary falls on a multiple of 32"), Index % 32, 0);
			}
		}
		TestEqual(TEXT("8 bands produce 7 transitions"), Transitions, 7);
	}

	return true;
}


/**
 * The GPU bridge's parity (renderer overhaul P3): the LUT texture bytes are
 * the authority's samples, bucket for bucket. This is the ONLY hop where
 * CFDViz::ColorMaps crosses to the renderer; the Slate legend and capture
 * burn-in read the CPU LUT directly, so this test is what makes "viewport,
 * legend and export cannot disagree" a checked property instead of a hope.
 */
IMPLEMENT_SIMPLE_AUTOMATION_TEST(
	FFlowVizColorMapTextureParityTest,
	"FlowViz.Render.ColorMapTextureParity",
	EAutomationTestFlags::EditorContext | EAutomationTestFlags::ClientContext
		| EAutomationTestFlags::EngineFilter)

bool FFlowVizColorMapTextureParityTest::RunTest(const FString& Parameters)
{
	const ECFDVizColorMap Maps[] = {
		ECFDVizColorMap::Viridis, ECFDVizColorMap::Plasma, ECFDVizColorMap::Inferno,
		ECFDVizColorMap::Magma, ECFDVizColorMap::CoolWarm, ECFDVizColorMap::BlueWhiteRed,
		ECFDVizColorMap::Grayscale, ECFDVizColorMap::Turbo
	};

	for (const ECFDVizColorMap Map : Maps)
	{
		TArray<FColor> Bytes;
		FlowVizColorMapTexture::BuildLutBytes(Map, Bytes);
		if (!TestEqual(TEXT("the LUT is full width"),
				Bytes.Num(), FlowVizColorMapTexture::LutWidth))
		{
			return false;
		}

		// Byte-level: each bucket is the authority sampled at ITS texel centre
		// and rounded -- the same arithmetic, reproduced independently here.
		int32 Mismatches = 0;
		for (int32 Index = 0; Index < Bytes.Num(); ++Index)
		{
			const float Position = (Index + 0.5f) / FlowVizColorMapTexture::LutWidth;
			if (Bytes[Index] != CFDViz::ColorMaps::Sample(Map, Position).QuantizeRound())
			{
				++Mismatches;
			}
		}
		TestEqual(FString::Printf(
			TEXT("map '%s': every texel matches the authority byte-for-byte"),
			*CFDViz::ColorMaps::GetName(Map).ToString()), Mismatches, 0);
	}

	// CONTROL: two different maps produce different bytes -- a BuildLutBytes
	// that ignored its argument would pass every parity check above.
	{
		TArray<FColor> A, B;
		FlowVizColorMapTexture::BuildLutBytes(ECFDVizColorMap::Viridis, A);
		FlowVizColorMapTexture::BuildLutBytes(ECFDVizColorMap::Turbo, B);
		TestTrue(TEXT("CONTROL: distinct maps yield distinct LUTs"), A != B);
	}

	return true;
}

#endif // WITH_DEV_AUTOMATION_TESTS
